name: "Push checks"
on:
  push:
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"

jobs:
  run_lint:
    name: "Run lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run lint
