name: "Tests"
on:
  # Manual trigger, in case want one-off run on a working branch
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "e2e/**"
      - "!e2e/.eslintrc.json"
      - "package.json"
      - "package-lock.json"

jobs:
  run_unit:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI

  run_tests:
    name: "Run e2e tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run postinstall
      - run: npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js
